version: '3'

services:

  mongoimport:
    image: mongo
    volumes:
      - ./mongo/data/users.json:/src/data/users.json
    command: mongoimport --host mongo --username root --password pwd --db admin --collection users --file /src/data/users.json --jsonArray

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
    depends_on:
      - mongoimport

  order-search-service:
    build:
      context: ${ORDER_SERVICE_PATH}
      dockerfile: Dockerfile
    image: order-search-service
    ports:
      - 8081:8080

  product-info-service:
    build:
      context: ${PRODUCT_SERVICE_PATH}
      dockerfile: Dockerfile
    image: product-info-service
    ports:
      - 8082:8080

  user-order-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-order-service
    ports:
      - 9090:9090
    depends_on:
      - order-search-service
      - product-info-service
      - mongo
